### ISSUE TITLE
VTR500 Support

### ISSUE THREAD

**Issue by AN3Orik** [Ztaeyn/HomeAssistant-VTR-Modbus#24]
Hi! First of all, ty for you work!
Your config supports VTR500 or i need do some thing to able to use with this vent unit?

**Comment by timkaTL** [comment]
Have VRT500 integrated into HA with serial modbus. it was required to redo register table as there are slight difference in comparison to VRT300.

**Comment by AN3Orik** [comment]
> Have VRT500 integrated into HA with serial modbus. it was required to redo register table as there are slight difference in comparison to VRT300.

Thanks for the answer. This differences are huge or just few parameters address/types? Maybe you have diff from original repo? For now this vent unit isn't connected to pipes and I can't power on to test.

**Comment by timkaTL** [comment]
there is a custom setup on my sire and only a few registers has been fixed. can share the config a bit latter today if interested.
in the nut shell it's necessary to check https://shop.systemair.com/upload/assets/SAVE_MODBUS_VARIABLE_LIST_20210301_REV36.PDF?2bf19ab8 and adjust the configuration file

**Comment by AN3Orik** [comment]
> there is a custom setup on my sire and only a few registers has been fixed. can share the config a bit latter today if interested. in the nut shell it's necessary to check https://shop.systemair.com/upload/assets/SAVE_MODBUS_VARIABLE_LIST_20210301_REV36.PDF?2bf19ab8 and adjust the configuration file

I will be very appreciated if you share just few addresses you changed comparing to this repository. Because i checked 10+ params from the end of datasheet (rev29 (using by this repo) and rev36 you mentioned) - and all this addresses is same for now.

**Comment by timkaTL** [comment]
this is what i have under config:
```
modbus:
  - name: modbus_hub
    type: serial
    port: /dev/ttyUSB3
    baudrate: 19200
    bytesize: 8
    method: rtu
    parity: E 
    stopbits: 1

    climates:
      - name: VRT500
        unique_id: vent_VRT500
        address: 12102
        slave: 1
        scale: 0.1
        offset: 0
        precision: 1
        max_temp: 30
        min_temp: 15
        temp_step: 1
        target_temp_register: 2000

    sensors:
        # All addresses are a number lower than value in MODBUS variable list
      - name: vrt500_outdoor_temperature
        unique_id: vrt500_outdoor_temperature
        device_class: temperature
        slave: 1
        address: 12101
        input_type: input
        unit_of_measurement: °C
        scale: 0.1
        offset: 0
        precision: 1
        data_type: int16

      - name: vrt500_supply_temperature
        unique_id: vrt500_supply_temperature
        device_class: temperature
        slave: 1
        address: 12102
        input_type: input
        unit_of_measurement: °C
        scale: 0.1
        offset: 0
        precision: 1
        data_type: uint16

      - name: vrt500_exhaust_temperature
        unique_id: vrt500_exhaust_temperature
        device_class: temperature
        slave: 1
        address: 12543
        input_type: input
        unit_of_measurement: °C
        scale: 0.1
        offset: 0
        precision: 1
        data_type: uint16

      - name: vrt500_relative_humidity_sensor
        unique_id: vrt500_relative_humidity_sensor
        device_class: humidity
        slave: 1
        address: 12135
        input_type: input
        unit_of_measurement: "%"
        data_type: uint16

      - name: vrt500_supply_air_fan_speed
        unique_id: vrt500_saf_speed_rpm
        slave: 1
        address: 12400
        input_type: input
        unit_of_measurement: rpm
        data_type: uint16

      - name: vrt500_exhaust_air_fan_speed
        unique_id: vrt500_eaf_speed_rpm
        slave: 1
        address: 12401
        input_type: input
        unit_of_measurement: rpm
        data_type: uint16

      - name: vrt500_supply_air_flow
        unique_id: vrt500_saf_flow
        slave: 1
        address: 12202
        input_type: input
        unit_of_measurement: "m³/h"
        data_type: uint16
        
      - name: vrt500_exhaust_air_flow
        unique_id: vrt500_eaf_flow
        slave: 1
        address: 12203
        input_type: input
        unit_of_measurement: "m³/h"
        data_type: uint16
```
